// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krmketgjjefutpvrxzws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtybWtldGdqamVmdXRwdnJ4endzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTI1NDYsImV4cCI6MjA2OTc4ODU0Nn0.RJp-FUJ3SGvYhNaUCRXf64jGKz2ECXQR3TFc8FR49vg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});